version: "3"

services:
  sonarqube:
      image: sonarqube:latest
      expose:
        - 9000
      container_name: sonarqube
      environment:
        - SONARQUBE_JDBC_USERNAME=sonar
        - SONARQUBE_JDBC_PASSWORD=sonar
        - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonar
      ports:
        - "9000:9000"
      networks:
        - sonarnet
      volumes:
        - sonarqube_conff:/opt/sonarqube/conf
        - sonarqube_dataa:/opt/sonarqube/data
        - sonarqube_extensionss:/opt/sonarqube/extensions
        - sonarqube_bundled-pluginss:/opt/sonarqube/lib/bundled-plugins 

  sonar-postgres:
    image: postgres:latest
    container_name: sonar-postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    ports:
      - "5432:5432"
    networks:
      - sonarnet
    volumes:
      - postgresqll:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  jenkis:
    image: jenkins/jenkins:latest
    container_name: jenkins
    privileged: true
    user: "1000:1000"
    ports: 
      - "8081:8081"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - sonarnet
networks:
  sonarnet:

volumes:
  sonarqube_conff:
  sonarqube_dataa:
  sonarqube_extensionss:
  sonarqube_bundled-pluginss:
  postgresqll:
  postgresql_data:
  jenkins_home: